name: Status check

on:
  pull_request:
  push:
    branches:
      - release # The release workflow will wait for this status check

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Validate PR title
        run: |
          # Get PR title
          PR_TITLE="${{ github.event.pull_request.title }}"
          PATTERN="^(?i)(feat|fix|docs|style|ci|refactor|perf|test|chore)(\([^\)]+\))?: .+$"
          if [[ ! "$PR_TITLE" =~ $PATTERN ]]; then
            echo "Invalid PR title. Must match Conventional Commits pattern: $PATTERN"
            echo "PR TITLE: $PR_TITLE"
            exit 1
          fi 
      - name: Install deps
        run: npm ci --include=optional
      - name: Lint check
        run: npm run lint:check # Check linting and apply possible fixes
      - name: Typecheck
        run: npm run tsc:noemit
      - name: Run tests
        run: npm run test
