name: Status check

on:
  pull_request:
  push:
    branches:
      - release # The release workflow will wait for this status check

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci --include=optional
      - name: Lint check
        run: npm run lint:check # Check linting and apply possible fixes
      - name: Typecheck
        run: npm run tsc:noemit
      - name: Run tests
        run: npm run test
