name: Publish prerelease

on:
  workflow_dispatch:
  push:
    branches: 
      - prerelease

jobs:
  prerelease:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - name: Install deps
        run: npm ci --include=optional
      - name: Prepare prerelease
        run: npm run prepare:prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Publish to npm
        run: npm run publish:prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
