name: Publish release

on:
  push:
    branches: 
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # needed for provenance data generation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          fetch-tags: true
      - name: Config GitHub user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - name: Install deps
        run: npm ci --include=optional
      - name: Prepare release and push commit
        run: |
          npm run release:prepare
          git push
          git checkout -b develop
          git merge main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Publish to npm
        run: npm run release:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
