name: Publish release

on:
  push:
    branches: 
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # needed for provenance data generation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.GH_TOKEN }}
      - name: Config GitHub user
        run: |
          git config user.name "flower-github-bot"
          git config user.email "flower-github-bot@users.noreply.github.com"
          git config push.autoSetupRemote true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - name: Wait for status check # Do not continue if the status check is not successful
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: checks
          repo-token: ${{ secrets.GH_TOKEN }}
          wait-interval: 20
      - name: Install deps
        run: npm ci --include=optional
      - name: Prepare release and push commit
        run: |
          npm run prepare:release
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Publish to npm
        run: npm run publish:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
      - name: Align main branch # Keep this step at the end in case of errors (e.g. merge conflicts)
        run: |
          git checkout -b main
          git merge release
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
